import { useState } from 'react'
import { ISSUE_ICONS } from '../../runbooks'

function formatResult(result) {
  if (!result) return '(no result)'
  if (typeof result === 'string') return result
  if (result.response)        return result.response
  if (result.text)            return result.text
  if (result.message)         return result.message
  // Fall back to pretty JSON
  return JSON.stringify(result, null, 2)
}

function buildNotes(wizard) {
  const now      = new Date()
  const dateStr  = now.toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })
  const category = wizard.category?.label || 'Unspecified'
  const site     = wizard.site?.name      || 'Unknown site'
  const reporter = wizard.reporter        || 'Unknown'
  const tech     = wizard.techName        || 'Unknown'
  const scope    = { individual: 'Individual user', multiple: 'Multiple users', site: 'Whole site' }[wizard.scope] || 'Unknown'
  const timeframe = wizard.timeframe || 'today'
  const included  = (wizard.queryResults || []).filter(r => r.included)

  const clientBlock = wizard.client
    ? [
        `Client name : ${wizard.client.username || wizard.client.hostname || wizard.client.mac || 'N/A'}`,
        wizard.client.mac  ? `MAC address : ${wizard.client.mac}`  : null,
        wizard.client.ip   ? `IP address  : ${wizard.client.ip}`   : null,
        wizard.client.ssid ? `SSID        : ${wizard.client.ssid}` : null,
        (wizard.client.family || wizard.client.os) ? `Device type : ${[wizard.client.family, wizard.client.os].filter(Boolean).join(' ')}` : null,
      ].filter(Boolean).join('\n')
    : 'Client      : (not specified — site-wide investigation)'

  const queryBlock = included.length > 0
    ? included.map(r =>
        `Query: ${r.query}\n` +
        `Result:\n${formatResult(r.result)}`
      ).join('\n\n' + '─'.repeat(60) + '\n\n')
    : '(no queries run)'

  const escalation = wizard.escalationGuidance
    ? `\nNOTE: ${wizard.escalationGuidance}`
    : ''

  return `MIST HELPDESK TICKET
${'='.repeat(60)}
Date        : ${dateStr}
Tech        : ${tech}
Reporter    : ${reporter}
Site        : ${site}
Scope       : ${scope}
Issue type  : ${category}
Timeframe   : Issue reported as starting ${timeframe}

${clientBlock}

ISSUE DESCRIPTION
${'─'.repeat(60)}
${wizard.description || '(none provided)'}

MARVIS INVESTIGATION
${'─'.repeat(60)}
${queryBlock}

ASSESSMENT & NEXT STEPS
${'─'.repeat(60)}
${escalation || ''}
[ Add your assessment and recommended next steps here before escalating ]

Generated by Mist Helpdesk Tool`
}

export default function NotesStep({ wizard, onBack, onReset }) {
  const [copied, setCopied] = useState(false)
  const notes = buildNotes(wizard)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(notes)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      /* fallback: select the text */
    }
  }

  return (
    <>
      <div className="question">Ticket notes</div>
      <div className="question-hint">
        Copy these into your ticketing system. Edit before sending — especially the assessment at the bottom.
      </div>

      <div className="notes-box">{notes}</div>

      <div className="copy-row">
        <button className="btn btn-primary" onClick={copy}>
          📋 Copy to clipboard
        </button>
        <span className={`copy-confirm ${copied ? 'show' : ''}`}>Copied!</span>
        <button className="btn btn-secondary" style={{ marginLeft: 'auto' }} onClick={onReset}>
          Start new ticket
        </button>
      </div>

      <div className="nav-row" style={{ borderTop: 'none', paddingTop: 0, marginTop: 16 }}>
        <button className="btn btn-ghost btn-sm" onClick={onBack}>← Back to investigation</button>
      </div>
    </>
  )
}
